### ISSUE TITLE
感觉说的不详细

### ISSUE THREAD

**Issue by haoxunba** [zry656565/vscode-debug-sample#1]
还是没有办法调试，端口根本就不行

**Comment by zry656565** [comment]
你是直接 clone 本项目的吗？你尝试的是 chrome 调试还是 node 程序调试？

**Comment by haoxunba** [comment]
@zry656565 chrome 对不起，之前的提问语气不好。调试为什么会牵扯到node？不是直接下载debugger for chrome 就可以调试了吗

**Comment by zry656565** [comment]
嗯，与此项目相关的这篇文章第三部分介绍了一些关于调试 node 服务器的内容。所以跟你确认一下。
你是调试这个例子遇到了问题，还是在自己的项目中想这么使用却失败了？

**Comment by haoxunba** [comment]
在我自己的demo中，我并没有使用node服务器。
因为 1. vscode不是说内置了node服务器吗？
2. 我就写个html文档，然后下载debugger for chrome插件，然后自动配置launch,启动调试的时候显示失败
3. 失败信息是`Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222`

您能帮我解决吗

**Comment by zry656565** [comment]
首先，vscode 只是一个功能稍微强大一点的编辑器，它支持直接调试 node 程序。但是，并没有所谓“内置”的说法，你还是要另外自己安装 node 环境。
我不太清楚你自己的 demo 的详情，我建议你直接 clone 本项目，按我所说的步骤运行起来。然后再琢磨琢磨为什么自己的 demo 跑不起来。

**Comment by deepred5** [comment]
新版的vscode直接支持nodemon调试了
```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "nodemon",
            "runtimeExecutable": "nodemon",
            "program": "${workspaceRoot}/index.js",
            "restart": true,
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }
    ]
}
```

**Comment by zry656565** [comment]
@deepred5 感谢你的建议，我抽空改善一下本项目。当然你直接提交一个 PR 也是非常欢迎的 :)

**Comment by zry656565** [comment]
@deepred5 已将该方法添加到项目中，谢谢！https://github.com/zry656565/vscode-debug-sample/commit/85bfe5591e4ef9250277e269769afdecc5aa30da
