### ISSUE TITLE
[DEP0062] DeprecationWarning: node --debug and node --debug-brk are invalid.

### ISSUE THREAD

**Issue by liyuhang1997** [zry656565/vscode-debug-sample#2]
# [DEP0062] DeprecationWarning: node --debug and node --debug-brk are invalid.

```bash
(node:21688) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
```

[Deprecated APIs | Node.js v10.1.0 Documentation](https://nodejs.org/api/deprecations.html#deprecations_dep0062_node_debug)
> `--debug` activates the legacy V8 debugger interface, which has been removed as of V8 5.8. It is replaced by Inspector which is activated with `--inspect` instead.

**Comment by zry656565** [comment]
Thanks! Removed in https://github.com/zry656565/vscode-debug-sample/commit/59bba44cefbab4391d8837c6bd3afe7dee0944dc

**Comment by zry656565** [comment]
抱歉，我思考了一下。目前低版本的 node 服务器还是普遍存在的，所以 `--debug` 还是有存在的意义。我把之前的修改 revert 掉啦。
